language: cpp

dist: bionic

compiler:
- gcc

os:
- linux

branches:
    only:
    - master

notifications:
    email: false

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install libboost-test-dev

script:
- cmake -B build -DCMAKE_BUILD_TYPE=Release -DELFIO_BUILD_EXAMPLES=YES -DELFIO_BUILD_TESTS=YES
- cmake --build build --config Release
- cd $TRAVIS_BUILD_DIR/ELFIO/build
- ctest -VV
- cd ..
