name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autoreconf
      run: autoreconf -i -f
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: cd tests
      run: cd tests
    - name: autoreconf tests
      run: autoreconf -i -f
    - name: configure tests
      run: ./cofigure
    - name: make tests
      run: make
    - name: make check for tests
      run: make check
    - name: return to root dir
      run: cd ..
    - name: make distcheck
      run: make distcheck
